version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./data:/app/data
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:80"
    depends_on:
      - backend
